namespace Calculator.Enums
{
    public enum CalculatorKeys
    {
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        ClearEntry,
        Clear,
        Divide,
        Multiply,
        Minus,
        Plus,
        Equal,
        Point,
        LeftParenthesis,
        RightParenthesis,
        Percent,
        Caret,
        SquareRoot
    }
}